name: realestate_email_aggregator_fe_vuejs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-lint-test-build-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run lint:ci
      - run: npm run test:unit
      - run: npm run build -- --mode development
      - name: fix code coverage paths
        run: |
          sed -i 's+/home/runner/work/ads_vue/ads_vue+/github/workspace+g' coverage/lcov.info
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
